name: med_journal
description: "Mediary â€” local-first medication and sleep journal with reminders."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  provider: ^6.1.0

  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.3

  # UI & Utilities
  intl: 0.20.2
  collection: ^1.18.0
  table_calendar: ^3.1.0
  timezone: ^0.9.0
  flutter_timezone: ^3.0.1

  # Notificaciones
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # Security
  local_auth: ^2.3.0

  # Sharing & Export
  share_plus: ^7.2.0
  csv: ^6.0.0
  pdf: ^3.11.1

  cupertino_icons: ^1.0.8
  excel: 4.0.6
  file_picker: ^10.3.8
  sqflite_sqlcipher: ^3.4.0
  sqlcipher_flutter_libs: ^0.6.8
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/icon.png
